### ISSUE TITLE
etcd-member is not running on startup

### ISSUE THREAD

**Issue by gunnaringe** [Quentin-M/etcd-cloud-operator#13]
Great work!

I have had some issues bootstrapping my etcd cluster, which seems to be due to the etcd-member service being down.

```
$ systemctl status eco
msg="STATUS: Healthy + Not running -> Join"
msg="failed to join the cluster" error="failed to add ourselves as a member ..."
```

This resolves instantly after running `systemctl start etcd-member`. Is eco supposed to start etcd itself, or should etcd-member be enabled and automatically run on startup?

**Comment by Quentin-M** [comment]
Hi,

`etcd-member.service` is a Container Linux specific systemd unit that is never used by the etcd-cloud-operator nor expected to be running. If you are using the provided Terraform module, `eco.service` is the sole service responsible for everything.

**Comment by gi-wg2** [comment]
Seems like I had managed to get my cluster in a bad state, but works fine now.

Feel free to close the issue, and thanks for providing this ;)

**Comment by Quentin-M** [comment]
Absolutely, I will be happy to help in any way possible.  Please feel free to patch as needed.
