### ISSUE TITLE
provider.aws: Not a valid region:

### ISSUE THREAD

**Issue by agentS5** [Quentin-M/etcd-cloud-operator#17]
Hi , 

First of all thanks for starting this project . Thumbs up for this great initiative

I am trying to setup an etcd cluster in the region us-east-1 using terraform.

terraform plan -out=etcd-cluster.tfplan

is outputing me the terraform plan file properly

But when I am applying changes to it I am getting the following error : 

**Error: Error applying plan:

1 error(s) occurred:

provider.aws: Not a valid region:** 

I am unable to figure out what is the issue here. I have provided the right region and all the configuration. I dont want a route53 entry and I have added true for internal load balancer and I dont want TLS for this cluster .

Can anyone please help me out , what needs to be done here ?

Thanks

**Comment by Quentin-M** [comment]
Hi there!

I am sorry I missed the e-mail. Have you sorted it out? It seems solely like a Terraform configuration issue as the Terraform code does not explicitly mention nor use regions at all, therefore relying 100% on your local AWS/TF configuration to pick a region to deploy the resources in.
