### ISSUE TITLE
Support Arbitary Ignition Config

### ISSUE THREAD

**Issue by captn3m0** [Quentin-M/etcd-cloud-operator#27]
Right now the entire ignition config is 

```hcl

data "ignition_config" "main" {
  files = [
    "${data.ignition_file.eco-config.id}",
    "${data.ignition_file.eco-ca.id}",
    "${data.ignition_file.eco-crt.id}",
    "${data.ignition_file.eco-key.id}",
    "${data.ignition_file.eco-health.id}",
    "${data.ignition_file.e.id}"
  ]

  systemd = [
    "${data.ignition_systemd_unit.docker.id}",
    "${data.ignition_systemd_unit.locksmithd.id}",
    "${data.ignition_systemd_unit.update-engine.id}",
    "${data.ignition_systemd_unit.eco.id}",
    "${data.ignition_systemd_unit.eco-health.id}",
    "${data.ignition_systemd_unit.node-exporter.id}",
  ]

  users = ["${data.ignition_user.core.id}"]
}
```

terraform ignition supports the [`append` block](https://www.terraform.io/docs/providers/ignition/d/config.html#append), which can be used to add arbitary ignition configuration. This would allow us to pass in additional users, groups or any other configuration without forking the repo.

If this sounds good, I can file a PR for this.

**Comment by Quentin-M** [comment]
That sounds great, absolutely!

**Comment by Quentin-M** [comment]
I am also open to granting maintainer rights, to whoever is actively contributing to their own forks. As I twitter [here](https://twitter.com/Quentin__M/status/1073466723443998720), many companies (incl. us) are using the operator, and I think that the community could greatly profit from any changes.

**Comment by captn3m0** [comment]
Filed PR: #28
