### ISSUE TITLE
Cluster lost quorum and didn't recover automatically.

### ISSUE THREAD

**Issue by empath75** [Quentin-M/etcd-cloud-operator#45]
health check for peer 1db1c9009069daa could not connect: dial tcp 10.194.214.86:2380: i/o timeout
2019-11-04 19:15:41.141040 W | etcdserver/membership: Reject add member request: the number of started member (2) will be less than the quorum number of the cluster (3)
2019-11-04 19:15:41.141076 W | etcdserver: not enough started members, rejecting member add {ID:9d2e3521595e019 RaftAttributes:{PeerURLs:[https://10.194.211.163:2380]} Attributes:{Name: ClientURLs:[]}}

A node terminated (the one with the timeout errors) and was replaced by the autoscaling group ( the one that was rejected), but the replacement couldn't join.  The only way I was able to fix it was by stopping the eco container on all the instances at the same time.

Is this something that should have been corrected automatically or was there another way to recover it?

**Comment by Quentin-M** [comment]
Have not bee able to respond here before. But that error message is expected. There is a configurable TTL, after which the dead instance will be *removed* from the quorum, allowing your new instance to join successfully. The [default](https://github.com/Quentin-M/etcd-cloud-operator/blob/64842826a4dcd90170c58d53d744a7754d461b1b/config.example.yaml#L5) is "30s" at the project-level and "3min" [on AWS](https://github.com/Quentin-M/etcd-cloud-operator/blob/8981d164776d611d1cc2b4eb4083459126ca34a5/terraform/platforms/aws/aws.tf#L88), which gives enough time for AWS EC2 instances to potentially restart / re-join.
