### ISSUE TITLE
Question using embedded server

### ISSUE THREAD

**Issue by tamalsaha** [Quentin-M/etcd-cloud-operator#7]
Thanks for this project. I want to use etcd with Kubernetes. Do you see using the embedded server a problem  given the speed to release of etcd?

**Comment by Quentin-M** [comment]
Sure thing, glad you find it useful!

The etcd-cloud-operator is what we use for all our Kubernetes clusters. Using the embedded server is not much different than using the etcd container images, or etcd binaries directly. When we want to update etcd, we simply need to bump the version in [glide.yaml](https://github.com/Quentin-M/etcd-cloud-operator/blob/378d8f2b829527561b5363691097994ed49e1f06/glide.yaml#L14) and re-build the etcd-cloud-operator image.

To update your etcd clusters, you'd simply have to bump the container image version in the Terraform module's configuration, terraform apply, and successively kill your EC2 nodes, waiting for new ones to start and rejoin. Once all the nodes are on the new etcd version, the etcd cluster will automatically switch to the updated etcd code/protocol.

**Comment by tamalsaha** [comment]
Thanks @Quentin-M 1
