### ISSUE TITLE
Publish muti-arch images

### ISSUE THREAD

**Issue by pschulten** [Quentin-M/etcd-cloud-operator#70]
It would be very nice, if you could also build and publish images for different architectures, e.g. `arm64` (aarch64)

**Comment by Quentin-M** [comment]
Fair enough. I should actually write a bit of automation too in order to be publishing images more consistently.

**Comment by Quentin-M** [comment]
A tad late, but done in https://github.com/Quentin-M/etcd-cloud-operator/commit/a3eef15581b21817917a8fe791d8e8a0822b37e6!
